### ISSUE TITLE
Crash when filtering with something that has empty parens, like a function name

### ISSUE THREAD

**Issue by Shenjoku** [campbellhome/bbserver#2]
I was recently trying to use the filter to search for a function name including the parens, and it causes it to crash. For example if you try to filter on "FuncName()". Looks like it crashes in `view_filter_convert_tokens_to_rpn()` with an invalid value in `stack.count`. Haven't looked into it beyond that.

**Comment by Shenjoku** [comment]
This crash is still happening. Any chance this can be fixed? @campbellhome

**Comment by campbellhome** [comment]
Apparently I missed this, sorry.  The crash is fixed in latest.  Searching for just FuncName() probably won't get you what you want though, unless you use quotes.
