### ISSUE TITLE
Blackbox client crashes when graphics device is lost

### ISSUE THREAD

**Issue by Shenjoku** [campbellhome/bbserver#3]
This tends to happen when connecting remotely, but it can also happen when reinstalling graphics drivers or from various other things that cause the graphics device to get lost. Not a major issue, just kind of annoying to deal with. If it could be fixed that would be great, if not, no big deal.

**Comment by campbellhome** [comment]
Can you provide a callstack?

**Comment by Shenjoku** [comment]
I can try, but I've never been able to nail down a solid repro. I'll see if I can figure it out :)

**Comment by Shenjoku** [comment]
Looks like this is fixed. Ever since updating to the newest version this doesn't happen anymore :)
