### ISSUE TITLE
Bug in bb_tick where it flushes every frame

### ISSUE THREAD

**Issue by Shenjoku** [campbellhome/bbserver#6]
In the logic of bb_tick it is never setting the value of s_lastFileFlushTime so it will flush the file every frame after it gets over the threshold for the first time. Need to add a line to update that variable every flush to fix it. Around line 840 in bb.c should be something like this:
```
if (now > s_lastFileFlushTime + kBBFile_FlushIntervalMillis)
{
	if (s_bb_flush_callback)
	{
		(*s_bb_flush_callback)(s_bb_flush_callback_context);
	}
	if (s_fp != BB_INVALID_FILE_HANDLE)
	{
		bb_file_flush(s_fp);
	}
	
	s_lastFileFlushTime = now; // This fixes the bug
}
```

**Comment by campbellhome** [comment]
Thanks, this should be fixed in latest.
