### ISSUE TITLE
Crash when loading a text file with some very long lines.

### ISSUE THREAD

**Issue by Shenjoku** [campbellhome/bbserver#7]
I've been running into a buffer overrun issue when trying to drag+drop text files into Blackbox. It seems to be a bit inconsistent in when it decides to crash. The only thing I know so far is that the problem is in `recorded_session_read_log()` at line 278. When the crash occurs, it is because the `decodeCursor` is 32767 and `recvCursor` is 327766. Since this math is clamping the value to `u16` and it ends up going negative, it wraps around to 65536 and causes it to write outside of the `session->recvBuffer` and then later crash. It's not immediately clear to me how the `decodeCursor` is getting so far ahead and I don't see any obvious fixes.

**Comment by Shenjoku** [comment]
Correction on this change: I also had to increase the buffer size of `bb_connection_s::recvBuffer` and the `recvBuffer` and `mbsBuffer` in `process_plaintext_file()` as well. Without this change it was impossible to open existing .bbox files.

It might be a good idea to make a constant for these buffers to make them easier to edit all in one go. Something like `kReceiveBufferSize` maybe.

**Comment by Shenjoku** [comment]
OK I take it back, changing the size of this buffer ends up breaking `recorded_session_read_thread()` because the length passed to `bbpacket_deserialize()` is `u16`, so 65536 goes outside of this range. This seems to be a bit harder to solve than I thought.

**Comment by Shenjoku** [comment]
Starting to think this crash has something to do with the logic at line 126:
```
if (bytesToRead % 2)
{
	--bytesToRead;
}
```

When this code makes it back up by one byte, if the `recvCursor` is at 32767 that ends up causing it to be 32766 when the `decodeCursor` is still 32767 and that results in the negative value. Still not quite sure how to solve this though.

**Comment by Shenjoku** [comment]
I don't know if this is a proper fix, but a quick fix that seemed to work was to change the `recvBuffer` and `mbsBuffer` sizes from 326768 + 1 to 326768 + 2. Giving it that extra byte appears to avoid the issue. Does this make sense to you @campbellhome ?

**Comment by campbellhome** [comment]
I added a fix that no longer crashes for my test case, and is clean in the ReleaseASan configuration.  Let me know if it still occurs for you.

**Comment by Shenjoku** [comment]
It no longer crashes, but it has an issue where it doesn't parse all of the lines. For some reason it always stops a little after 1000 lines. I'm trying to figure out how to send you a sample file to test with, but it has too much sensitive information in it. Looking into finding an obfuscator or something to just randomize all of the characters but no luck so far.

**Comment by Shenjoku** [comment]
[Test.log](https://github.com/user-attachments/files/17601806/Test.log)

Here we go, attached a randomized log file that has the problem. It stops showing after line 1034 but there are many many more.

**Comment by Shenjoku** [comment]
@campbellhome FYI, attached a test file for a related issue. I couldn't figure out how to fix it myself.

**Comment by campbellhome** [comment]
Just getting to this.  That line is 121,056 chars long!  If you take that out, the file parses entirely.  I just committed a fix that should work for lines < 256k.
