### ISSUE TITLE
Blackbox client accepting connections from all servers on the network

### ISSUE THREAD

**Issue by Shenjoku** [campbellhome/bbserver#8]
I've been having a strange problem since getting the latest code where the blackbox client will accept connections from everyone on the network instead of just the localhost. I have a suspicion it has something to do with this new value that is showing in the whitelist:
0: (allow) ::1 (mask ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff) application: ''

That appears to be some new addition along with the ipv6 support that was added. I don't really understand where that value is coming from or how to prevent it from matching every single IP that comes through. Any suggestions?

**Comment by campbellhome** [comment]
I don't see that - the only auto-created entry I see is for "localhost", which is added in config_validate_whitelist.  Can you pinpoint where your whitelist entry is coming from?

**Comment by campbellhome** [comment]
I see where it comes from.  I filtered it out so let me know how it works for you now.

**Comment by Shenjoku** [comment]
Aha! I found the bug. The problem is in find_whitelist_match() at line 73. It's checking the family of the wrong variable where it's doing:
resolved_whitelist_entry_t* entry = host->whitelist.data + i;
if (sin->ss_family == AF_INET)
it should be:
resolved_whitelist_entry_t* entry = host->whitelist.data + i;
if (entry->addr.ss_family == AF_INET)

**Comment by campbellhome** [comment]
Thanks!  That is fixed now.  For good measure, I added a config combo box (under advanced) to control listening to ipv4, ipv6, or both.
